name: fishy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  adaptive_theme: ^3.1.1
  stylish_bottom_bar: ^1.0.0
  animated_checkmark: ^1.0.1
  animations: ^2.0.7
  auth_buttons:
    git:
      url: https://github.com/elbeicktalat/flutter_auth_buttons.git
      ref: main
  auto_route: ^5.0.4
  chips_choice: ^3.0.0
  cloud_firestore: ^4.5.0
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  dismissible_page: ^1.0.1
  pull_down_button: ^0.8.3
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  firebase_ui_auth: ^1.2.0
  firebase_ui_firestore: ^1.3.0
  dio: ^5.1.1
  retrofit: ^4.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  bot_toast: ^4.0.3
  flutter_image_compress: ^1.1.3
  cached_network_image: ^3.2.3
  draggable_home:
    git: https://github.com/gidrokolbaska/draggable_home
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_location_marker:
    git: https://github.com/gidrokolbaska/flutter_map_location_marker
  flutter_map_marker_cluster:
    git: https://github.com/gidrokolbaska/flutter_map_marker_cluster_fix_marker_tap
  flutter_map_tile_caching: ^8.0.0
  flutter_riverpod: ^2.1.3
  riverpod_annotation:
  flutter_svg: ^2.0.1
  flutter_vibrate: ^1.3.0
  form_builder_validators: ^9.0.0
  geolocator: ^9.0.2
  #google_fonts: ^3.0.1

  google_sign_in: ^6.0.0
  flutter_slidable: ^3.0.0
  intl: ^0.18.0
  introduction_screen: ^3.1.4
  latlong2: ^0.8.1
  modal_bottom_sheet: ^3.0.0-pre
  multi_image_picker_view:
    git: https://github.com/gidrokolbaska/multi_image_picker_view
  path_provider: ^2.0.14
  rive: ^0.10.2
  shared_preferences: ^2.0.17
  sizer: ^2.0.15
  uni_links: ^0.5.1
  url_launcher: ^6.1.8
  vertical_weight_slider: ^2.4.0
  grouped_list: ^5.1.2
  simple_grouped_listview: ^2.0.0

dev_dependencies:
  icons_launcher: ^2.1.3
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  retrofit_generator: ^6.0.0+3
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  package_rename: ^1.0.0+1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FishyIcons
      fonts:
        - asset: fonts/FishyIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
