name: fishy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  adaptive_theme: ^3.1.1
  animations: ^2.0.7
  auth_buttons: ^3.0.0
  auto_route: ^5.0.4
  # calendar_date_picker2:
  #   git: https://github.com/gidrokolbaska/calendar_date_picker2_fix_border_radius
  cloud_firestore: ^4.4.2
  connectivity_plus: ^3.0.3
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_ui_auth: ^1.1.13
  firebase_ui_firestore: ^1.2.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_map_location_marker:
    git: https://github.com/gidrokolbaska/flutter_map_location_marker
  flutter_map_marker_cluster:
    git: https://github.com/gidrokolbaska/flutter_map_marker_cluster_fix_marker_tap
  flutter_map_tile_caching: ^7.0.2
  flutter_riverpod: ^2.1.3
  flutter_svg: ^1.1.6
  flutter_vibrate: ^1.3.0
  form_builder_validators: ^8.4.0
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_sign_in: ^6.0.0
  intl: ^0.17.0
  introduction_screen: ^3.1.4
  latlong2: ^0.8.1
  modal_bottom_sheet: ^3.0.0-pre
  rive: ^0.10.2
  shared_preferences: ^2.0.17
  sizer: ^2.0.15
  uni_links: ^0.5.1
  url_launcher: ^6.1.8
  vertical_weight_slider: ^2.4.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  package_rename: ^1.0.0+1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FishyIcons
      fonts:
        - asset: fonts/FishyIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
